# Generated by Django 2.2.2 on 2021-08-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0002_event_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_login',
            field=models.CharField(blank=True, max_length=50, verbose_name='Логин'),
        ),
    ]
